# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'httparty', '0.21.0'
gem 'nokogiri', '1.16.2'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'rubocop-rspec'
  gem 'timecop'
  gem 'webmock'
end
