# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'httparty', '0.17.3'
gem 'nokogiri', '1.15.4'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'rubocop-rspec'
  gem 'timecop'
  gem 'webmock'
end
